[project]
name = "ezib-async"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ib-async>=1.0.3",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=0.26.0",
]
